server:
  port: 9071
  servlet:
    context-path: /hcm

spring:
  application:
    name: Conure HCM Web
#  For deployment in any environment, let say stage, dev or Prod
  datasource:
    url: jdbc:postgresql://localhost:5432/conurets_hcm_latest
    username: postgres
    password: Irtaza300515
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-circular-references: true

logging:
  file.name: /logs/hcm.web.log
  pattern:
    console: "%d{ISO8601} [%d{z}] - %-5p [%t]: [%C] %m%n"
    file: "%d{ISO8601} [%d{z}] - %-5p [%t]: [%C] %m%n"
  level:
    root: INFO
    org.springframework.*: INFO
    com.conurets.hcm.*: INFO


