version: '3'
services:
  hcm_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hcm_backend
    restart: always
    networks:
      - default_vm_network
    environment:
      #Postgresql db credentials
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_default/conurets_hcm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=conure123
    ports:
      - "9071:9071"
networks :
  default_vm_network:
    external: true
